testbench.v
lab_407_top.v
Gen_st.v
./slave/SPI_SLAVE.v
./display/DISPLAY.v
./display/D7seg.v
./display/Gen_P.v
./display/Gen1ms.v
./display/Gen4an.v
./display/MUX16_4.v
./master/SPI_MASTER.v
./master/FTR.v
./master/FSR.v
./master/cb_bit.v
./master/cb_tact.v
./master/MRX_DAT.v
./master/sr_MRX.v
./master/sr_MTX.v
./master/syn_gen.v
